theme: jekyll-theme-slate
title: EnvironmentAll
description: Climate Change Visualized Outside Your Home
show_downloads: true
tagline: Site Tagline
author :
	  name : Name Lastname
	  email : blah@email.test
	  github : username
	  twitter : username
	  feedburner : feedname
